Feature/implement database
Dmitry993/TestTask pull request #2
Opened 2020-01-21 15:57 UTC by Dmitry993

2020-01-21 17:05 UTC, dd221x0 requested changes

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Models/ApplicationUserDb.cs
> +    public class ApplicationUserDb
это не Db, назови просто User

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Models/ApplicationUserDb.cs
> +        public string Password { get; set; }
тут разве будет пароль?

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Repositories/UserRepository.cs
> +            return _context.Users;
добавь `.ToList()` иначе оно вернет орм объект

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Repositories/UserRepository.cs
> +        private bool disposed = false;
все поля должны объявляться в начале класса

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Profiles/ApplicationUserProfile.cs
> +                .ForMember(b => b.Id, opt => opt.MapFrom(b => b.Id))
не нужно конфигурировать каждое поле, они автоматически мапятся если названы одинаково

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/IUserService.cs
> +        IEnumerable<ApplicationUser> GetAllUser();
GetAllUser**s**

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/IUserService.cs
> +        ApplicationUser Get(int id);
чтобы было консистентно с предыдущим методом - `GetUser`

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +        private readonly IMapper _mapper;
Соблюдай один стиль везде, если в одном месте приватные поля начинаются с подчеркивания - так должно быть во всем проекте. Либо везде без подчеркивания

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +        private readonly IMapper _mapper;
я больше предпочитаю без подчеркивания и обращаться через `this.<имя>`

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +            _repository.Create(_mapper.Map<ApplicationUserDb>(item));
выноси отдельные действия в переменные, так код более читабелен

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/AutofacModule.cs
> +        {
А где регистрация контекста? автомаппера?

2020-01-21 17:05 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Startup.cs
> -                app.UseDeveloperExceptionPage();
DeveloperExceptionPage может быть полезна, не стоит убирать. Зачем в целом был удален хендлинг?

2020-01-21 17:05 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Startup.cs
> +                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
зачем это?

2020-01-21 17:05 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Startup.cs
> +            services.AddDbContext<NewsPortalDbContext>(options =>
Давай перенесем в автофак конфиг, чтобы везде использовался один IoC контейнер.

2020-01-21 17:06 UTC, shaeredal commented
В целом неплохо.

2020-01-23 11:23 UTC, dd221x0 requested changes

2020-01-23 11:23 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Controllers/AuthController.cs
> +            if (userInfo.Id != null && !(await _userService.UserExist(userInfo.Id)))
это бизнес логика, ее место в другом слое

2020-01-23 11:23 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Controllers/AuthController.cs
> +                _userService.CreateUser(CreateNewUser(userInfo));
если юзер уже есть, надо его авторизовать

2020-01-23 11:23 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Controllers/AuthController.cs
> +        public ApplicationUser CreateNewUser(UserInfo userInfo)
Бизнес логика должна быть в слое бизнес логики.
Методы использующиеся только внутри класса - не должны быть `public`.

2020-01-23 11:23 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Repositories/IRepository.cs
> +        Task<IEnumerable<T>> GetAll();
Помечай асинхронные методы постфикcом `Async`

2020-01-23 11:23 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Repositories/UserRepository.cs
> +            return await _context.Users.ToListAsync();
Зачем тут асинхронный метод?

2020-01-23 11:23 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/IUserService.cs
> +        Task<IEnumerable<ApplicationUser>> GetAllUser();
Почему каакие-то методы синхронные какие-то асинхронные? Тут есть какая-то логика?

2020-01-23 11:23 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +            var users = await _repository.GetAll();
`id` юзера должен обновится в модели, на надо искать его.

2020-01-23 11:23 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +        public async Task<string> FindUserByGoogleId(string id)
это лучше реализовать на уровне репозитория

2020-01-23 11:23 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +            if (result == null)
можно написать проще `return result?.Id.ToString()`

2020-01-23 11:23 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Controllers/AuthController.cs
> +                var findUserId =  await _userService.FindUserByGoogleId(userInfo.Id);
бизнес логика должна быть в своем слое а не здесь

2020-01-23 11:28 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Repositories/UserRepository.cs
> +        private bool disposed = false;
_disposed

2020-01-23 14:05 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +using ApplicationUser = NewsPortal.Logic.Model.ApplicationUser;
почему не просто `using NewsPortal.Logic.Model`?

2020-01-24 10:52 UTC, dd221x0 requested changes

2020-01-24 10:52 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Profiles/UserProfile.cs
> +﻿using AutoMapper;
название папки не описывает то что ней находится, поменяй на `Mappers`

2020-01-24 10:52 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/IUserService.cs
> +        Task<IEnumerable<ApplicationUser>> GetAllUserAsync();
уже писал - User_s_

2020-01-24 10:52 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +        public async Task<string> GetUserIdAsync(ApplicationUser item)
метод называется `GetUserId`, почему в нем создается новый пользователь?

2020-01-24 10:52 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Startup.cs
> +            services.AddAutoMapper(typeof(ApplicationUser).Assembly, typeof(UserProfile).Assembly);
`ApplicationUserProfile`

2020-01-24 10:52 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Repositories/UserRepository.cs
> +            var user = await _context.Users.FirstOrDefaultAsync(b =>b.GoogleId == id);
пробел после =>

2020-01-24 10:52 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +        public async Task<string> GetUserIdAsync(ApplicationUser item)
public async Task<int> GetOrCreateUserAsync(ApplicationUser applicationUser)
        {            
            var user = await _repository.FindUserByGoogleIdAsync(item.GoogleId);

            if (user == null)
            {
                CreateUser(user);        
            }

            return user.Id;
        }              

        public async Task<ApplicationUser> GetUserAsync(int id)
        {
            var user = await _repository.GetAsync(id);
            return _mapper.Map<ApplicationUser>(user);
        }

        public async Task<IEnumerable<ApplicationUser>> GetAllUserAsync()
        {
            var usersList = await _repository.GetAllAsync();
            return _mapper.Map<IEnumerable<User>, IEnumerable<ApplicationUser>>(usersList);
        }
        
        private async Task<int> CreateUser(user)
        {
              var user = _mapper.Map<User>(ApplicationUser applicationUser);
              await _repository.CreateAsync(user);
              await _repository.SaveAsync();     
        }

2020-01-24 11:30 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +        public async Task<string> GetUserIdAsync(ApplicationUser item)
Исправил, изменил метод GetUserId, удалил лишний запрос в базу в CreateUserAsync

2020-01-24 11:35 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Repositories/UserRepository.cs
> +            var user = await _context.Users.FirstOrDefaultAsync(b =>b.GoogleId == id);
добавил

2020-01-24 11:36 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Startup.cs
> +            services.AddAutoMapper(typeof(ApplicationUser).Assembly, typeof(UserProfile).Assembly);
дописал Profile

2020-01-24 11:38 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/IUserService.cs
> +        Task<IEnumerable<ApplicationUser>> GetAllUserAsync();
дописал "s"

2020-01-24 11:39 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Profiles/UserProfile.cs
> +﻿using AutoMapper;
переименовал

2020-01-24 11:40 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +using ApplicationUser = NewsPortal.Logic.Model.ApplicationUser;
возможно вижла добавила, сейчас убрал

2020-01-24 12:36 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/UserService.cs
> +            if (result == null)
уже неактуально

2020-01-24 12:37 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Controllers/AuthController.cs
> +                var findUserId =  await _userService.FindUserByGoogleId(userInfo.Id);
уже сделано

2020-01-24 12:38 UTC, dd221x0 requested changes

2020-01-24 12:38 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Controllers/AuthController.cs
> +                var id = await _userService.GetOrCreateUserAsync(user);
пусть лучше юзера возвращает, а id тут из проперти брать

2020-01-24 12:51 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Controllers/AuthController.cs
> +                var id = await _userService.GetOrCreateUserAsync(user);
поменял, теперь возвращают юзера

2020-01-24 13:08 UTC, merged