Feature/implement post comments
Dmitry993/TestTask pull request #6
Opened 2020-02-04 16:27 UTC by Dmitry993

2020-02-06 16:41 UTC, dd221x0 requested changes
Поревьювал что успел. Завтра продолжу.

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Models/Comment.cs
> +        public int? PostId { get; set; }
PostId - non-nullable, он обязательно должен быть

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Models/Comment.cs
> +        public string UserName { get; set; }
Не нужно дублировать данные в разных таблицах.
Все связи должны быть по Id и только по нему, что если UserName изменится?

Тут должен быть UserId.
Если нужен UserName - его нужно взять из таблицы Users по Id

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Context/NewsPortalDbContext.cs
> +using Microsoft.EntityFrameworkCore.Migrations;
Она тут используется?
Удаляй все неиспользуемые зависимости.

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Repositories/CommentRepository.cs
> +            if (comment != null)
Ставь фигурные скобки даже если в блоке только одна строка.

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Repositories/IPostRepository.cs
> +
пустая строка

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Model/UserComment.cs
> +    public class UserComment
просто Comment

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +        public async Task<IEnumerable<UserComment>> GetPostCommentsAsync(int id)
назови параметр postId, чтобы было четко понятно чей это id

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +            var userComments = _mapper.Map<List<UserComment>>(comments);
Сделай нормальный нейминг.
Чем `comments` отличаются от `userComments`?

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +            foreach (var item in userComments)
Это все должно происходит на уровне данных.
Не нужно забирать все коменты чтобы потом использовать только часть их.
Сначала забираешь все комментарии к посту: `_context.Comments.Where(comment => comment.PostId == postId)`, и тут уже из них делаешь дерево.
Что-то вроде этого:

> var addChilds = comment => {
>     comment.Childs = postComments.Where(comment => comment.ParentId == id);
>     comment.Childs.forEach(addChilds);
>     };
> 
> var topComments = postComments.Where(comment => comment.ParentId == null);
> var topComments.forEach(addChilds);

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +        public async Task<UserComment> CreateCommentAsync(UserComment userComment)
userComment - имя ни о чем не говорит

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +    public class AddCommentComponent : ViewComponent
CommentEditor

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +            var stringId = HttpContext.Request.Cookies["UserId"];
userIdString

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +            var id = Int32.Parse(stringId);
userId

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +            var user = await _userService.GetUserAsync(id);
не нужно ничего из базы таскать тут, UserName тут не нужен

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +            return View("/Views/Comment/CreateComment.cshtml", comment);
вью и компонент должны называться одинаково, в чем вообще смысл называть их по разному?

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +                if (item.PostId == id & item.ParentId == null)
почитай чем отличаются битовые и логические операторы, тут должно быть `&&`

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +                if(postComments.Any(comment => comment.Id == item.ParentId))
абсолютно не нужная проверка

2020-02-06 16:41 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Model/UserComment.cs
> +        public List<UserComment> Reply { get; set; } = new List<UserComment>();
Все списки должны называться в множественном числе - `Replies`.

2020-02-06 16:41 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Components/CommentListComponent.cs
> +            if (postId == 0 & commentId == 0)
Битовый оператор.
Что если postId == null?
что если commentId == 0 а postId != 0?

2020-02-06 16:41 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Components/CommentListComponent.cs
> +                return View("/Views/Home/Index.cshtml");
Должна отображаться ошибка. Тут будет рендериться целая страница где должен быть этот компонент

2020-02-07 07:14 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Context/NewsPortalDbContext.cs
> +using Microsoft.EntityFrameworkCore.Migrations;
Я обычно удаляю, но иногда забываю. 
Когда все исправлю, пройдусь по проекту и поудаляю

2020-02-07 07:15 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Models/Comment.cs
> +        public int? PostId { get; set; }
исправил

2020-02-07 07:19 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Repositories/CommentRepository.cs
> +            if (comment != null)
Ок

2020-02-07 07:20 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Repositories/IPostRepository.cs
> +
убрал

2020-02-07 07:30 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Model/UserComment.cs
> +        public List<UserComment> Reply { get; set; } = new List<UserComment>();
Это я знаю. Видимо, был невнимателен

2020-02-07 07:37 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +            foreach (var item in userComments)
Я забирал все комменты, потому что изначально выводил их для всех постов на начальную страницу. Буду переделывать

2020-02-07 09:45 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +                if (item.PostId == id & item.ParentId == null)
Ок

2020-02-07 09:46 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +                if(postComments.Any(comment => comment.Id == item.ParentId))
Согласен, убрал

2020-02-07 09:47 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +        public async Task<UserComment> CreateCommentAsync(UserComment userComment)
изменил на comment

2020-02-07 10:28 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Model/UserComment.cs
> +    public class UserComment
переименовал

2020-02-07 12:12 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +            var id = Int32.Parse(stringId);
изменил

2020-02-07 12:12 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +            var stringId = HttpContext.Request.Cookies["UserId"];
изменил

2020-02-07 12:13 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +            var user = await _userService.GetUserAsync(id);
убрал

2020-02-07 12:29 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +    public class AddCommentComponent : ViewComponent
переименовал

2020-02-07 12:31 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/AddCommentComponent.cs
> +            return View("/Views/Comment/CreateComment.cshtml", comment);
Согласен, логичнее называть одинаково

2020-02-07 12:38 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Models/Comment.cs
> +        public string UserName { get; set; }
переделал, связал модели в контексте и добавил свойство узера в модель коммента

2020-02-07 12:44 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +            var userComments = _mapper.Map<List<UserComment>>(comments);
переделал

2020-02-07 12:56 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/CommentService.cs
> +        public async Task<IEnumerable<UserComment>> GetPostCommentsAsync(int id)
ок

2020-02-07 13:48 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/CommentListComponent.cs
> +                return View("/Views/Home/Index.cshtml");
ок

2020-02-07 13:51 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/CommentListComponent.cs
> +            if (postId == 0 & commentId == 0)
уже не актуально

2020-02-10 13:24 UTC, merged