Feature/implement rating
Dmitry993/TestTask pull request #7
Opened 2020-02-11 11:01 UTC by Dmitry993

2020-02-11 12:48 UTC, dd221x0 requested changes

2020-02-11 12:48 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Models/Rating.cs
> +    public class Rating
Переименуй в PostRating, потому что будет еще рейтинг для комментов

2020-02-11 12:48 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Models/Rating.cs
> +        public int Value { get; set; }
можно boolean где true - "+", false - "-"

2020-02-11 12:48 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Repositories/PostRepository.cs
> +            return await _context.Posts
Лучше создать отдельное поле в Post и обновлять его вмместе с таблицей PostRatings чтобы каждый раз не делать запросы в PostRatings

2020-02-11 12:48 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Repositories/RatingRepository.cs
> +    public class RatingRepository : IRatingRepository
В репозиториях много дублирования кода, может сделать абстрактный класс куда вынести все что повторяется?

2020-02-11 12:48 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Models/Rating.cs
> +    public class Rating
Эта модель не нужна, мы не будем вывозить каждую оценку отдельно

2020-02-11 12:48 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +        public async Task<Rating> UpPostRatingAsync(int postId)
дублирование кода с `DownPostRatingAsync`, добавь параметр или вынеси в отдельный метод

2020-02-11 12:48 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +                Value = post.Rating.Value += 1
получается юзер может поставить больше 1 оценки, это есть неправильно

2020-02-11 12:48 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Controllers/RatingController.cs
> +        {
можно сделать 1 экшн с параметромм вместо 2, и вообще это все можно перенести в PostController

2020-02-11 14:25 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Models/Rating.cs
> +    public class Rating
ок

2020-02-11 14:25 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Models/Rating.cs
> +        public int Value { get; set; }
изменил

2020-02-11 14:26 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Models/Rating.cs
> +    public class Rating
удалил

2020-02-11 14:26 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +        public async Task<Rating> UpPostRatingAsync(int postId)
удалил и создал новый метод

2020-02-11 14:27 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +                Value = post.Rating.Value += 1
проверку еще не добавлял, сейчас сделаю

2020-02-11 14:28 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Controllers/RatingController.cs
> +        {
сделал один экшен

2020-02-12 11:34 UTC, dd221x0 requested changes

2020-02-12 11:34 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Controllers/RatingController.cs
> +            var userClicked = await _service.UserClickedRatingAsync(postId, userId);
бизнес логика в контроллере

2020-02-12 11:34 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Repositories/RatingRepository.cs
> +        public async Task DeleteItemByPostIdAndUserId(int postId, int userId)
не надо в названии расписывать все параметры

2020-02-12 11:34 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Components/PostRatingComponent.cs
> +            if (userClicked == true)
if (userClicked) 
{
    return ...
}
else
{
    return...
}

2020-02-12 11:34 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Components/PostRatingComponent.cs
> +            var userClicked = await _ratingService.UserClickedRatingAsync(postId, userId);
название переменных должно быть существительным

2020-02-12 11:34 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/PostService.cs
> +        public async Task UpdatePostRatingAsync(int postId, bool? value, bool? cancelValue)
зачем 2 параметра `value` и `cancelValue`?

if(value)
{
   rating++;
}
else
{
    rating--;
}

2020-02-12 11:50 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Repositories/RatingRepository.cs
> +        public async Task DeleteItemByPostIdAndUserId(int postId, int userId)
изменил

2020-02-12 14:39 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Controllers/RatingController.cs
> +            var userClicked = await _service.UserClickedRatingAsync(postId, userId);
логику перенес в сервис

2020-02-12 15:29 UTC, dd221x0 requested changes

2020-02-12 15:29 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Repositories/IRatingRepository.cs
> +        Task<PostRating> FindItemByPostId(int postId, int userId);
Назови просто FindItem 🙂

2020-02-12 15:29 UTC, dd221x0 commented on NewsPortal/NewsPortal.Data/Repositories/IRatingRepository.cs
> +        Task DeleteItemByPostId(int postId, int userId);
то же самое, DeleteItem

2020-02-12 15:29 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Models/Rating.cs
> +        Add = 1,
`None`,
`Minus`,
`Plus`

это не вычитание и добавление, enum должен просто описыввать сущности

2020-02-12 15:29 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Models/Rating.cs
> +﻿using System;
это не модель, перенеси в отдельную папку `Enums`

2020-02-12 15:29 UTC, dd221x0 commented on NewsPortal/NewsPortal.Logic/Services/PostService.cs
>                  post.Rating += 1;
не принципиально, но можно было `++` вместо `+= 1`

2020-02-12 15:29 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/PostService.cs
> +        public async Task UpdatePostRatingAsync(int postId, Rating value)
Идея в том, чтобы сервис никак не зависел от реализации рейтинга.
Тут как раз можно сделать 2 метода `IncreaseRating` и `DecreaseRating` которые будут в пару строк и вызывать их из RatingService. 

Кстати апдейт можно тоже вынести в отдельный метод на уровне репозитория чтобы писать 1 строку вместо 2.
`_repository.UpdateAndSave(post);`

2020-02-12 15:29 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +            var rating = await _repository.FindItemByPostId(postId, userId);
`rating` и `Rating` выглядят почти одинаково, а сущности совершенно разные, нужно придумать имена получше

2020-02-12 15:29 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +        public async Task<Rating> UserClickedRatingAsync(int postId, int userId, Rating value)
Название тоже никак не отражает то, что делает метод.

2020-02-12 15:29 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +            var ratingValue = rating != null ? (Rating)rating.Value : Rating.Nothing;
он возвращает предыдущее значение рейтинга?
можно упростить кстати - `return rating == null ? Rating.Nothing : (Rating)rating.Value`

2020-02-12 15:29 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Components/PostRatingComponent.cs
> +            if (userClick.Equals(Rating.Add))
с enum можно использовать switch

2020-02-13 06:55 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Repositories/IRatingRepository.cs
> +        Task<PostRating> FindItemByPostId(int postId, int userId);
изменил

2020-02-13 06:55 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Repositories/IRatingRepository.cs
> +        Task DeleteItemByPostId(int postId, int userId);
ок

2020-02-13 06:57 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Models/Rating.cs
> +        Add = 1,
изменил

2020-02-13 06:57 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Models/Rating.cs
> +﻿using System;
ок

2020-02-13 07:01 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/PostService.cs
>                  post.Rating += 1;
ок

2020-02-13 07:03 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/PostService.cs
> +        public async Task UpdatePostRatingAsync(int postId, Rating value)
добавил

2020-02-13 07:10 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +            var ratingValue = rating != null ? (Rating)rating.Value : Rating.Nothing;
ок

2020-02-13 07:27 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/PostRatingComponent.cs
> +            if (userClick.Equals(Rating.Add))
переделал со свитч

2020-02-13 11:13 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +        public async Task<Rating> UserClickedRatingAsync(int postId, int userId, Rating value)
разбил на два метода и переименовал

2020-02-13 11:14 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/RatingService.cs
> +            var rating = await _repository.FindItemByPostId(postId, userId);
переименовал

2020-02-13 11:58 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/IRatingService.cs
> +        Task AddOrCancelRatingAsync(int postId, int userId, Rating value);
просто UpdateRating

2020-02-13 12:18 UTC, merged