Feature/implement sort
Dmitry993/TestTask pull request #9
Opened 2020-02-14 16:55 UTC by Dmitry993

2020-02-19 09:32 UTC, dd221x0 requested changes

2020-02-19 09:32 UTC, dd221x0 commented on NewsPortal/NewsPortal.Web/Components/PostListComponent.cs
> +            var sortedPosts = _postService.SortPosts(
Сделай метод `GetSortedPosts` который будет идти в базу данных и забирать сразу отсортированные посты. LINQ to SQL преобразует `OrderBy` на orm объектах в `ORDER BY` в SQL. Это будет лучше по перформансу и не надо будет обращаться к сервису несклько раз.

2020-02-19 09:32 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Views/Home/UserProfile.cshtml
> +    <div class="row">
Сортировка должна работать на уровне `PostList`, а не дублироваться на каждой странице

2020-02-19 15:10 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/PostListComponent.cs
> +            var sortedPosts = _postService.SortPosts(
добавил метод

2020-02-19 15:11 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Views/Home/UserProfile.cshtml
> +    <div class="row">
перенес сортировку в PostList

2020-02-20 09:15 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Repositories/IPostRepository.cs
> +        IEnumerable<Post> GetSortedPosts<T>(int userId, Func<Post, T> expression, bool isDescending);
```suggestion
        IEnumerable<Post> GetSortedPosts<T>(int userId, Func<Post, T> keySelector, bool isDescending);
```

2020-02-20 09:15 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Repositories/PostRepository.cs
> +                ? _context.Posts.Where(post => post.AuthorId == userId || userId == 0).ToList()
LINQ составляет запрос припомощи LINQ to SQL и выполняет его только тогда, когда данные запрашиваются (lazy loading). `ToList()` - один из вариантов это сделать. То есть после вызова `ToList()` ты работаешь уже не с query а с коллекцией данных.
Перенеси сортировку перед `ToList()`.

2020-02-20 09:15 UTC, shaeredal commented on NewsPortal/NewsPortal.Data/Repositories/PostRepository.cs
> +                : _context.Posts.Where(post => post.AuthorId == userId || userId == 0).ToList()
Не нужно писать 2 раза одно и то же, тебе нужно только в конце прицепить нужный ордеринг.

2020-02-20 09:15 UTC, shaeredal commented on NewsPortal/NewsPortal.Logic/Services/PostService.cs
> +                case SortBy.Date when !isDescending:
Передавай isDescending сразу в метод.
Если у тебя куча одинакового кода как здесь - ты определенно делаешь что-то не так.
Тут должен быть ровно 1 вызов `GetSortedPosts`

2020-02-20 09:15 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Components/PostListComponent.cs
> +        public async Task<IViewComponentResult> InvokeAsync(int userId, SortBy sort, ListSortDirection direction)
Сделай однообразным. Если юзаешь `ListSortDirection`, делай это везде. Хотя лучше все таки `bool`.

2020-02-20 09:28 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Repositories/PostRepository.cs
> +                ? _context.Posts.Where(post => post.AuthorId == userId || userId == 0).ToList()
ок

2020-02-20 09:32 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Repositories/PostRepository.cs
> +                : _context.Posts.Where(post => post.AuthorId == userId || userId == 0).ToList()
ок

2020-02-20 09:45 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Logic/Services/PostService.cs
> +                case SortBy.Date when !isDescending:
убрал лишнее из метода

2020-02-20 10:05 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Components/PostListComponent.cs
> +        public async Task<IViewComponentResult> InvokeAsync(int userId, SortBy sort, ListSortDirection direction)
поменял на бул

2020-02-20 10:05 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Data/Repositories/IPostRepository.cs
> +        IEnumerable<Post> GetSortedPosts<T>(int userId, Func<Post, T> expression, bool isDescending);
поменял

2020-02-20 10:24 UTC, dd221x0 requested changes

2020-02-20 10:24 UTC, shaeredal commented on NewsPortal/NewsPortal.Web/Controllers/HomeController.cs
> +            ViewData["direction"] = isDescending;
Строку тоже нужно поменять на "isDescending"

2020-02-20 10:31 UTC, Dmitry993 commented on NewsPortal/NewsPortal.Web/Controllers/HomeController.cs
> +            ViewData["direction"] = isDescending;
ок

2020-02-20 10:35 UTC, merged